### ISSUE TITLE
ProtocolError

### ISSUE THREAD

**Issue by frankbp** [google/mobly#70] opened 2017-01-03 10:47 UTC
When running the sample test, it raises ProtocolError, and SL4A server is started

self._start_jsonrpc_client(self.sl4a, host_port, device_port)
  File "/Library/Python/2.7/site-packages/mobly/controllers/android_device.py", line 598, in _start_jsonrpc_client
    client.connect(port=host_port)
  File "/Library/Python/2.7/site-packages/mobly/controllers/android_device_lib/jsonrpc_client_base.py", line 214, in connect
    raise ProtocolError(ProtocolError.NO_RESPONSE_FROM_HANDSHAKE)
ProtocolError: No response from handshake.
[SampleTestBed] 01-03 18:45:57.005 ERROR No response from handshake.
[SampleTestBed] 01-03 18:45:57.005 INFO [Test Case] setup_class FAIL
[SampleTestBed] 01-03 18:45:57.006 INFO Summary for test run SampleTestBed@01-03-2017_18-45-52-772: Error 0, Executed 1, Failed 1, Passed 0, Requested 1, Skipped 0
frankbp:Downloads xielieping$ adb devices
List of devices attached
P4M0214A08001775	device

**Comment by xpconanfan** [comment] 2017-01-03 18:43
Thanks for reporting!
Could you share the complete log output, including the adb logcat?

**Comment by frankbp** [comment] 2017-01-04 01:21
it is HUAWEI Mate7, model is "HUAWEI MT7-TL00" while the system is Android4.4.2

log output:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/mobly/base_test.py", line 504, in run
    self._setup_class()
  File "/Library/Python/2.7/site-packages/mobly/base_test.py", line 128, in _setup_class
    self.setup_class()
  File "hello_world_test.py", line 11, in setup_class
    self.ads = self.register_controller(android_device)
  File "/Library/Python/2.7/site-packages/mobly/test_runner.py", line 331, in register_controller
    objects = create(controller_config)
  File "/Library/Python/2.7/site-packages/mobly/controllers/android_device.py", line 88, in create
    _start_services_on_ads(ads)
  File "/Library/Python/2.7/site-packages/mobly/controllers/android_device.py", line 135, in _start_services_on_ads
    ad.start_services(skip_sl4a=getattr(ad, KEY_SKIP_SL4A, False))
  File "/Library/Python/2.7/site-packages/mobly/controllers/android_device.py", line 412, in start_services
    self._start_sl4a()
  File "/Library/Python/2.7/site-packages/mobly/controllers/android_device.py", line 572, in _start_sl4a
    self._start_jsonrpc_client(self.sl4a, host_port, device_port)
  File "/Library/Python/2.7/site-packages/mobly/controllers/android_device.py", line 598, in _start_jsonrpc_client
    client.connect(port=host_port)
  File "/Library/Python/2.7/site-packages/mobly/controllers/android_device_lib/jsonrpc_client_base.py", line 214, in connect
    raise ProtocolError(ProtocolError.NO_RESPONSE_FROM_HANDSHAKE)
ProtocolError: No response from handshake.
[SampleTestBed] 01-04 09:18:39.565 ERROR No response from handshake.
[SampleTestBed] 01-04 09:18:39.565 INFO [Test Case] setup_class FAIL
[SampleTestBed] 01-04 09:18:39.566 INFO Summary for test run SampleTestBed@01-04-2017_09-18-35-320: Error 0, Executed 1, Failed 1, Passed 0, Requested 1, Skipped 0

logcat in attachment
[logcat.txt](https://github.com/google/mobly/files/683698/logcat.txt)

**Comment by dthkao** [comment] 2017-01-04 01:42
I believe you're using Damon Kolher's old version of sl4a? If so, it's most likely is incompatible. I'd suggest using the updated version from the AOSP repo, under project <aosp>/external/sl4a.

**Comment by xpconanfan** [comment] 2017-01-04 01:43
Thanks for the logs.

It looks like you're using an SL4A obtained from the original SL4A project, which is not compatible with our code.
Make sure you build sl4a from Android repo as instructed in README, as the Android repo SL4A requires system privilege.

If you're using a 'user' build, you will not be able to use the Android repo SL4A at all, in which case it might be better to skip SL4A entirely. To do so, in config:
```
"AndroidDevice": [
  {"serial": <serial>, "skip_sl4a": true}
]
```

Without SL4A, you can still control the android device with adb calls and [Mobly Snippets](https://github.com/google/mobly-snippet-lib). (P.S. We are working on a general snippet implementation to cover basic Android operations.)

**Comment by frankbp** [comment] 2017-01-04 01:50
thanks for the reply, is there any compatible SL4A APK available?

**Comment by xpconanfan** [comment] 2017-01-04 01:53
Unfortunately if you're not using Nexus device userdebug builds, no.
But if you have access to the source code of the Android build you're using, you could easily build the SL4A apk you need for your device.

If you don't need to make system privileged calls, you don't need SL4A. FYI, basic operations like connecting to a Wi-Fi network don't actually require system privilege.

**Comment by frankbp** [comment] 2017-01-04 02:04
then if i can find the nexus device where can i get the sl4a apk file instead of building it from source?

**Comment by xpconanfan** [comment] 2017-01-04 02:07
Ah, sorry I just realized I probably could not share our internal SL4A apks...
Note you'll need a **userdebug** build of Nexus device, not just any build.
If you have a userdebug build for Nexus, you could probably easily build SL4A for it already :)

**Comment by xpconanfan** [comment] 2017-01-04 02:08
Sorry about the trouble.
I've filed #73 to make this less painful.

**Comment by xpconanfan** [comment] 2017-01-05 17:11
So, can you specify what operations you are trying to perform with SL4A?
Perhaps I could implement as a snippet for you.

**Comment by frankbp** [comment] 2017-01-06 07:29
since I am only in evaluation stage, you can build the snippet for me with any basic operation support, thanks.

**Comment by xpconanfan** [comment] 2017-01-06 09:35
I have sent an apk to your email address with basic Wi-Fi controls.
In your test bed config, use `skip_sl4a` option as previously stated.
In your test, try the following:
```
ad = self.register_controller(android_device)[0]
ad.load_snippet('api', 'com.google.android.mobly.snippet.api')
ad.api.wifiEnable()
ad.api.wifiDisable()
```

**Comment by frankbp** [comment] 2017-01-06 12:02
thanks.
with the apk given I can successfully run the test but from the console seems like cleanup failed.

[SampleTestBed] 01-06 18:04:24.988 INFO ==========> HelloWorldTest <==========
[SampleTestBed] 01-06 18:04:25.374 INFO [Test Case] test_hello
[SampleTestBed] 01-06 18:04:27.163 INFO Stopping snippet apk with: am instrument -w -e action stop com.google.android.mobly.snippet.api/com.google.android.mobly.snippet.SnippetRunner
[SampleTestBed] 01-06 18:04:28.944 INFO Launching snippet apk with: am instrument -e action start -e port 7748 com.google.android.mobly.snippet.api/com.google.android.mobly.snippet.SnippetRunner
[SampleTestBed] 01-06 18:04:31.802 INFO [Test Case] test_hello PASS
[SampleTestBed] 01-06 18:04:31.802 INFO Summary for test class HelloWorldTest: Error 0, Executed 1, Failed 0, Passed 1, Requested 1, Skipped 0
[SampleTestBed] 01-06 18:04:31.803 ERROR [AndroidDevice|P4M0214A08001775] Failed to clean up properly.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/mobly/controllers/android_device.py", line 100, in destroy
    ad.stop_services()
  File "/Library/Python/2.7/site-packages/mobly/controllers/android_device.py", line 420, in stop_services
    self.stop_adb_logcat()
  File "/Library/Python/2.7/site-packages/mobly/controllers/android_device.py", line 694, in stop_adb_logcat
    utils.stop_standing_subprocess(self._adb_logcat_process)
  File "/Library/Python/2.7/site-packages/mobly/utils.py", line 353, in stop_standing_subprocess
    _assert_subprocess_running(proc)
  File "/Library/Python/2.7/site-packages/mobly/utils.py", line 304, in _assert_subprocess_running
    " stdout: %s" % (proc.pid, ret, err, out))
Error: Process 11711 has terminated. ret: 0, stderr: , stdout:
[SampleTestBed] 01-06 18:04:31.804 INFO Summary for test run SampleTestBed@01-06-2017_18-04-24-986: Error 0, Executed 1, Failed 0, Passed 1, Requested 1, Skipped 0

**Comment by dthkao** [comment] 2017-01-06 17:27
Is there any chance you have (or reproduce) a logcat from that?

**Comment by xpconanfan** [comment] 2017-01-06 18:05
Could you also share the test code you used as well?

**Comment by frankbp** [comment] 2017-01-07 04:32
script:
from mobly import base_test
from mobly import test_runner
from mobly.controllers import android_device

class HelloWorldTest(base_test.BaseTestClass):

  def setup_class(self):
    # Registering android_device controller module declares the test's
    # dependency on Android device hardware. By default, we expect at least one
    # object is created from this.
    
    #self.ads = self.register_controller(android_device)
    #self.dut = self.ads[0]

    ad = self.register_controller(android_device)
    self.dut = ad[0]
    

  def test_hello(self):
  	self.dut.load_snippet('api', 'com.google.android.mobly.snippet.api')
  	self.dut.api.wifiEnable()
  	self.dut.api.wifiDisable()
    #self.dut.sl4a.makeToast('Hello World!')

if __name__ == "__main__":
  test_runner.main()

config file:
{
    "testbed":
    [
        {
            "_description": "A testbed where adb will find Android devices.",
            "name": "SampleTestBed",
            "AndroidDevice": [
                {"serial": "P4M0214A08001775", "skip_sl4a": true}
            ]
        }
    ],
    "logpath": "/tmp/logs"
}

**Comment by xpconanfan** [comment] 2017-01-07 06:36
I was able to run the same script with no problem.
```
$ python HelloWorldTest.py -c config.txt
[SampleTestBed] 01-06 22:34:26.487 INFO ==========> HelloWorldTest <==========
[SampleTestBed] 01-06 22:34:29.462 INFO [Test Case] test_hello
[SampleTestBed] 01-06 22:34:29.990 INFO Stopping snippet apk with: am instrument -w -e action stop com.google.android.mobly.snippet.api/com.google.android.mobly.snippet.SnippetRunner
[SampleTestBed] 01-06 22:34:36.651 INFO Launching snippet apk with: am instrument -e action start -e port 8693 com.google.android.mobly.snippet.api/com.google.android.mobly.snippet.SnippetRunner
[SampleTestBed] 01-06 22:34:39.268 INFO [Test Case] test_hello PASS
[SampleTestBed] 01-06 22:34:39.269 INFO Summary for test class HelloWorldTest: Error 0, Executed 1, Failed 0, Passed 1, Requested 1, Skipped 0
[SampleTestBed] 01-06 22:34:39.273 INFO Stopping snippet apk with: am instrument -w -e action stop com.google.android.mobly.snippet.api/com.google.android.mobly.snippet.SnippetRunner
[SampleTestBed] 01-06 22:34:40.085 INFO Summary for test run SampleTestBed@01-06-2017_22-34-26-486: Error 0, Executed 1, Failed 0, Passed 1, Requested 1, Skipped 0
```

Are you sure you're using the latest Mobly?
If you have the code cloned, try
```$ sudo python setup.py develop```
Then run the test again and see if it helps.

**Comment by frankbp** [comment] 2017-01-09 01:28
I was installing mobly through pip, so do I need to use lasted develop branch?

**Comment by xpconanfan** [comment] 2017-01-09 03:47
Ah, I see.
Depending on when you installed it.
We just released 1.1 recently.
If you can, using ToT might be better since we are constantly making bug fixes and improvements :)
Release train is a bit slower.

**Comment by frankbp** [comment] 2017-01-09 05:28
thanks for your quick response.
would it be OK to have your skype account so that we can chat more easier, mine is frankbp

P.S i saw your google gtac 2016 video on youtube :-)

**Comment by xpconanfan** [comment] 2017-01-09 06:32
Unfortunately I'm almost never on skype...
We're figuring out a way to have more interactively support external customers. Perhaps an IRC channel. Stay tuned :)

If there's no further question, shall we close this thread?

**Comment by frankbp** [comment] 2017-01-10 01:25
pls close this thread, thanks for your help

**Closed** 2017-01-10 01:26 UTC
Labels: customer issue
